name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  backend-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Start FastAPI (background)
        run: |
          nohup bash -lc 'PYTHONPATH=backend uvicorn app:app --app-dir backend --host 127.0.0.1 --port 8000' >/dev/null 2>&1 &

      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:8000/health >/dev/null; then
              echo "Server is up"; exit 0
            fi
            sleep 1
          done
          echo "Server failed to start in time"; exit 1

      - name: Smoke test /health
        run: |
          curl -sS http://127.0.0.1:8000/health | tee /tmp/health.json
          echo "Health JSON above"

      - name: Verify JSON fields
        run: |
          python - <<'PY'
import json, sys
data = json.load(open("/tmp/health.json"))
assert data.get("ok") is True, "ok != True"
assert "version" in data, "missing version"
print("Health checks passed:", data)
PY
